name: Deploy Backend to Elastic Beanstalk

on:
  push:
    branches: [ master ]
    paths:
      - 'razorlinks/**'
      - '.github/workflows/deploy-backend.yml'

# Required for OIDC authentication
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::735189764250:role/GitHubActionsRazorlinksRole
          role-session-name: github-actions-razorlinks-deploy
          aws-region: ap-south-1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x razorlinks/gradlew

      - name: Build with Gradle
        working-directory: ./razorlinks
        run: ./gradlew clean build -x test

      - name: Get current timestamp
        id: timestamp
        run: echo "time=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          application_name: Razorlinks-sb
          environment_name: Razorlinks-sb-env
          region: ap-south-1
          version_label: razorlinks-${{ steps.timestamp.outputs.time }}
          deployment_package: razorlinks/build/libs/razorlinks-0.0.1-SNAPSHOT.jar
          wait_for_deployment: true
          wait_for_environment_recovery: 300

      - name: Deployment successful
        if: success()
        run: echo "✅ Backend deployed successfully to Elastic Beanstalk!"

      - name: Deployment failed
        if: failure()
        run: echo "❌ Deployment failed. Check the logs above for details."